name: Java CI with Gradle

on:
  push:
    branches:
      - transfer-new
  pull_request:
    branches:
      - transfer-new

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: adopt
          java-version: 11
      - name: Build LimboAuth
        run: ./gradlew build
      - name: Upload LimboAuth
        uses: actions/upload-artifact@v3.0.0
        with:
          name: LimboAuth
          path: "build/libs/limboauth*.jar"
